[tox]
envlist = py311,py312,py313,py314
skipsdist = false
isolated_build = true
useuv = true

[testenv]
allowlist_externals = uv
commands = python -m pytest --cov --cov-report=html
deps = pytest
       coverage
       pytest-cov
       pytest-mock
       pytest-asyncio
