#!/usr/bin/env python3
"""Update README coverage badge from coverage.py JSON output."""

from __future__ import annotations

import argparse
import json
import logging
import re
from pathlib import Path

logger = logging.getLogger(__name__)

BADGE_PATTERN = re.compile(
    r"!\[Coverage\]\(https://img\.shields\.io/badge/coverage-[^)]+\)"
)
BRIGHTGREEN_THRESHOLD = 90
GREEN_THRESHOLD = 80
YELLOWGREEN_THRESHOLD = 70
YELLOW_THRESHOLD = 60
ORANGE_THRESHOLD = 50


def badge_color(percent: int) -> str:
    if percent >= BRIGHTGREEN_THRESHOLD:
        return "brightgreen"
    if percent >= GREEN_THRESHOLD:
        return "green"
    if percent >= YELLOWGREEN_THRESHOLD:
        return "yellowgreen"
    if percent >= YELLOW_THRESHOLD:
        return "yellow"
    if percent >= ORANGE_THRESHOLD:
        return "orange"
    return "red"


def parse_coverage_percent(coverage_json: Path) -> float:
    data = json.loads(coverage_json.read_text(encoding="utf-8"))
    total = data.get("totals", {})
    percent_value = total.get("percent_covered")
    if not isinstance(percent_value, int | float):
        msg = f"Could not read totals.percent_covered from {coverage_json}"
        raise TypeError(msg)
    return round(percent_value, 2)


def render_badge(percent: float) -> str:
    color = badge_color(percent)
    return f"![Coverage](https://img.shields.io/badge/coverage-{percent}%25-{color})"


def update_readme(readme_path: Path, badge_markdown: str) -> bool:
    content = readme_path.read_text(encoding="utf-8")
    match = BADGE_PATTERN.search(content)

    if match:
        updated = BADGE_PATTERN.sub(badge_markdown, content, count=1)
    else:
        lines = content.splitlines()
        if not lines:
            msg = f"README is empty: {readme_path}"
            raise ValueError(msg)
        lines.insert(1, badge_markdown)
        updated = "\n".join(lines) + "\n"

    if updated == content:
        return False

    readme_path.write_text(updated, encoding="utf-8")
    return True


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--coverage-json",
        default="coverage.json",
        help="Path to coverage JSON generated by coverage.py/pytest-cov.",
    )
    parser.add_argument(
        "--readme",
        default="README.md",
        help="Path to README file containing coverage badge.",
    )
    return parser.parse_args()


def main() -> int:
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    args = parse_args()

    coverage_json = Path(args.coverage_json)
    readme_path = Path(args.readme)

    percent = parse_coverage_percent(coverage_json)
    badge = render_badge(percent)
    changed = update_readme(readme_path, badge)

    if changed:
        logger.info("Updated README coverage badge to %s%%", percent)
    else:
        logger.info("README coverage badge already up to date at %s%%", percent)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
